# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LocalstackPackagedCli < Formula
  desc "Localstack cli packaged using pyinstaller"
  homepage "https://github.com/alexrashed/localstack-packaged-cli"
  url "https://github.com/alexrashed/localstack-packaged-cli/archive/v2.0.3.dev20230523065743.tar.gz"
  sha256 "cd7efdccba17dbf71a34459bfac1ce65a8580539a7cbabb655a864de9293da5c"

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"localstack"
  end

  test do
    assert_match /LocalStack Command Line Interface/, shell_output("#{bin}/localstack --help", 0)
  end
end
