# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LocalstackCli < Formula
  desc "Localstack cli packaged using pyinstaller"
  homepage "https://github.com/alexrashed/localstack-cli"
  url "https://github.com/alexrashed/localstack-cli/archive/v2.1.0.tar.gz"
  sha256 "5e678345889e305dcd1f14dfe506f7d4361fe27ab44a4a9563f614d1b40beb98"

  on_macos do
    on_intel do
      url "https://github.com/alexrashed/localstack-cli/releases/download/v2.1.0/localstack-cli-2.1.0-darwin-amd64.tar.gz"
      sha256 "4389718d79e8cbec4e4e856d8679a9279907949295d63b49fbd12aefc8677727"
    end

    on_arm do
      url "https://github.com/alexrashed/localstack-cli/releases/download/v2.1.0/localstack-cli-2.1.0-darwin-arm64.tar.gz"
      sha256 "4389718d79e8cbec4e4e856d8679a9279907949295d63b49fbd12aefc8677727"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexrashed/localstack-cli/releases/download/v2.1.0/localstack-cli-2.1.0-linux-amd64.tar.gz"
      sha256 "9a5e1b37ede7aaab6eb65d51ccbd6dc5c9bf2d8b1507b0b5ab757bfbeaafa81d"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"localstack"
  end

  test do
    assert_match /LocalStack Command Line Interface/, shell_output("#{bin}/localstack --help", 0)
  end
end
