# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LocalstackPackagedCli < Formula
  desc "Localstack cli packaged using pyinstaller"
  homepage "https://github.com/alexrashed/localstack-packaged-cli"
  url "https://github.com/alexrashed/localstack-packaged-cli/archive/v2.0.3.dev20230524094841.tar.gz"
  sha256 "811236ecba811693e73cebe9924bb6a31b81bd99dceeee7c96ab4a1c5ec157a0"

  on_macos do
  end

  on_linux do
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"localstack"
  end

  test do
    assert_match /LocalStack Command Line Interface/, shell_output("#{bin}/localstack --help", 0)
  end
end
