# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LocalstackPackagedCli < Formula
  desc "Localstack cli packaged using pyinstaller"
  homepage "https://github.com/alexrashed/localstack-packaged-cli"
  url "https://github.com/alexrashed/localstack-packaged-cli/archive/v2.0.3.dev.tar.gz"
  sha256 "f92d7a07aef3d61bb11aac6c3a21f0daff7ab94dfb1cc62a45d456c1aa8a853b"

  on_macos do
  end

  on_linux do
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"localstack"
  end

  test do
    assert_match /LocalStack Command Line Interface/, shell_output("#{bin}/localstack --help", 0)
  end
end
