# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class LocalstackCli < Formula
  desc "Localstack cli packaged using pyinstaller"
  homepage "https://github.com/alexrashed/localstack-cli"
  url "https://github.com/alexrashed/localstack-cli/archive/v2.0.3.dev20230524094841.tar.gz"
  sha256 "ecf470d250d7e8f4e5fd7601a825137b328178746607a7eeccb21e8770195fbe"

  on_macos do
  end

  on_linux do
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"localstack"
  end

  test do
    assert_match /LocalStack Command Line Interface/, shell_output("#{bin}/localstack --help", 0)
  end
end
